export const products = [
  {
    'id': 246016548,
    'title': 'Навигационная система Soundmax',
    'category': 'Техника для дома',
    'units': 'шт',
    'count': 5,
    'price': 100,
    'sum': 500,
  },
  {
    'id': 937295527,
    'title': 'Настольная игра “На 4-х ногах”',
    'category': 'Настольные игры',
    'units': 'шт',
    'count': 12,
    'price': 14,
    'sum': 168,
  },
  {
    'id': 246016549,
    'title': 'Навигационная система Soundmax',
    'category': 'Техника для дома',
    'units': 'шт',
    'count': 5,
    'price': 100,
    'sum': 500,
  },
  {
    'id': 246016550,
    'title': 'Навигационная система Soundmax',
    'category': 'Техника для дома',
    'units': 'шт',
    'count': 5,
    'price': 100,
    'sum': 500,
  },
];
